# -*- coding: utf-8 -*-
"""
Legacy source generator.

DO NOT RUN during normal development. This script appends C++ source directly
to aichatwidget.h and can corrupt the current refactored AI chat module.
"""
import argparse
import sys

parser = argparse.ArgumentParser(description="Legacy AiChatWidget source appender.")
parser.add_argument(
    "--i-know-this-modifies-source",
    action="store_true",
    help="Required because this script appends directly to source files.",
)
args = parser.parse_args()

if not args.i_know_this_modifies_source:
    print(
        "Refusing to run: tools/legacy/gen_aichat.py appends directly to "
        "aichatwidget.h. Re-run only with --i-know-this-modifies-source if "
        "you intentionally want that legacy side effect.",
        file=sys.stderr,
    )
    sys.exit(2)

out = open('D:/MyQtProject/QtMediaPlayer/aichatwidget.h', 'a', encoding='utf-8', newline='\n')
def w(s): out.write(s + '\n')
w('    void appendBubble(ChatBubble::Role role, const QString &text,')
w('                      const QPixmap &thumb = QPixmap())')
w('    {')
w('        ChatBubble *b = new ChatBubble(role, text, thumb, m_scrollContent);')
w('        m_chatLayout->addWidget(b);')
w('        QTimer::singleShot(50, this, [this](){')
w('            m_scrollArea->verticalScrollBar()->setValue(m_scrollArea->verticalScrollBar()->maximum());')
w('        });')
w('    }')
w('    void showThinking()')
w('    {')
w('        if (m_thinking) return;')
w('        m_thinking = new ThinkingBubble(m_scrollContent);')
w('        m_chatLayout->addWidget(m_thinking);')
w('        QTimer::singleShot(50, this, [this](){')
w('            m_scrollArea->verticalScrollBar()->setValue(m_scrollArea->verticalScrollBar()->maximum());')
w('        });')
w('    }')
w('    void removeThinking()')
w('    {')
w('        if (!m_thinking) return;')
w('        m_chatLayout->removeWidget(m_thinking);')
w('        m_thinking->deleteLater();')
w('        m_thinking = nullptr;')
w('    }')
w('    void captureFrame()')
w('    {')
w('        if (!m_videoWidget) {')
w('            m_statusLabel->setText(QString("\u89c6\u9891\u63a7\u4ef6\u672a\u521d\u59cb\u5316"));')
w('            return;')
w('        }')
w('        QScreen *screen = QGuiApplication::primaryScreen();')
w('        QPixmap px;')
w('        if (screen) {')
w('            QPoint gp = m_videoWidget->mapToGlobal(QPoint(0,0));')
w('            px = screen->grabWindow(0, gp.x(), gp.y(), m_videoWidget->width(), m_videoWidget->height());')
w('        }')
w('        if (px.isNull() || px.width() == 0)')
w('            px = m_videoWidget->grab();')
w('        if (px.isNull()) {')
w('            m_statusLabel->setText(QString("\u622a\u56fe\u5931\u8d25"));')
w('            return;')
w('        }')
w('        m_pendingPixmap = px;')
w('        QPixmap scaled = px.scaled(m_thumbLabel->width(), m_thumbLabel->height(),')
w('                                   Qt::KeepAspectRatio, Qt::SmoothTransformation);')
w('        m_thumbLabel->setPixmap(scaled);')
w('        m_statusLabel->setText(QString("\u5df2\u622a\u56fe\uff0c\u53ef\u8f93\u5165\u95ee\u9898\u53d1\u9001"));')
w('    }')
w('    void clearImage()')
w('    {')
w('        m_pendingPixmap = QPixmap();')
w('        m_thumbLabel->setPixmap(QPixmap());')
w('        m_thumbLabel->setText(QString("\u6682\u65e0\u622a\u56fe\n\u70b9\u51fb\u4e0b\u65b9\u6309\u9215\u622a\u53d6\u5f53\u524d\u753b\u9762"));')
w('        m_statusLabel->setText("");')
w('    }')
w('    void sendMessage()')
w('    {')
w('        if (m_requesting) return;')
w('        QString text = m_inputEdit->toPlainText().trimmed();')
w('        if (text.isEmpty() && m_pendingPixmap.isNull()) {')
w('            m_statusLabel->setText(QString("\u8bf7\u8f93\u5165\u95ee\u9898\u6216\u622a\u53d6\u753b\u9762"));')
w('            return;')
w('        }')
w('        appendBubble(ChatBubble::User, text, m_pendingPixmap);')
w('        m_inputEdit->clear();')
w('        QPixmap sentPixmap = m_pendingPixmap;')
w('        clearImage();')
w('        m_requesting = true;')
w('        m_btnSend->setEnabled(false);')
w('        m_statusLabel->setText(QString("AI \u6b63\u5728\u601d\u8003\u4e2d..."));')
w('        showThinking();')
w('        callQwenAPI(text, sentPixmap);')
w('    }')
w('    void callQwenAPI(const QString &question, const QPixmap &pixmap)')
w('    {')
w('        QNetworkRequest request;')
w('        request.setUrl(QUrl(m_apiUrl));')
w('        request.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");')
w('        request.setRawHeader("Authorization", QString("Bearer %1").arg(m_apiKey).toUtf8());')
w('        QJsonArray contentArr;')
w('        if (!pixmap.isNull()) {')
w('            QByteArray imgBytes;')
w('            QBuffer buf(&imgBytes);')
w('            buf.open(QIODevice::WriteOnly);')
w('            pixmap.save(&buf, "JPEG", 85);')
w('            buf.close();')
w('            QJsonObject imgPart;')
w('            imgPart["type"] = "image_url";')
w('            QJsonObject imgUrl;')
w('            imgUrl["url"] = QString("data:image/jpeg;base64,") + QString::fromLatin1(imgBytes.toBase64());')
w('            imgPart["image_url"] = imgUrl;')
w('            contentArr.append(imgPart);')
w('        }')
w('        QJsonObject textPart;')
w('        textPart["type"] = "text";')
w('        textPart["text"] = question.isEmpty() ? QString("\u8bf7\u5206\u6790\u8fd9\u4e2a\u753b\u9762\u7684\u5185\u5bb9") : question;')
w('        contentArr.append(textPart);')
w('        QJsonObject userMsg;')
w('        userMsg["role"] = "user";')
w('        userMsg["content"] = contentArr;')
w('        QJsonObject sysMsg;')
w('        sysMsg["role"] = "system";')
w('        sysMsg["content"] = QString("\u4f60\u662f\u4e13\u4e1a\u5f71\u89c6\u5206\u6790\u52a9\u624b\uff0c\u80fd\u8bc6\u522b\u753b\u9762\u4eba\u7269\u3001\u573a\u666f\u548c\u5267\u60c5\uff0c\u7528\u4e2d\u6587\u56de\u7b54\u95ee\u9898\u3002");')
w('        QJsonArray messages;')
w('        messages.append(sysMsg);')
w('        messages.append(userMsg);')
w('        QJsonObject body;')
w('        body["model"] = m_model;')
w('        body["messages"] = messages;')
w('        body["max_tokens"] = 1024;')
w('        QNetworkReply *reply = m_network->post(request, QJsonDocument(body).toJson(QJsonDocument::Compact));')
w('        connect(reply, &QNetworkReply::finished, this, [this, reply](){ onReplyFinished(reply); });')
w('    }')
w('    void onReplyFinished(QNetworkReply *reply)')
w('    {')
w('        removeThinking();')
w('        m_requesting = false;')
w('        m_btnSend->setEnabled(true);')
w('        m_statusLabel->setText("");')
w('        if (reply->error() != QNetworkReply::NoError) {')
w('            appendBubble(ChatBubble::Assistant, QString("\u8bf7\u6c42\u5931\u8d25\uff1a") + reply->errorString());')
w('            reply->deleteLater(); return;')
w('        }')
w('        QByteArray data = reply->readAll();')
w('        reply->deleteLater();')
w('        QJsonParseError pe;')
w('        QJsonDocument doc = QJsonDocument::fromJson(data, &pe);')
w('        if (pe.error != QJsonParseError::NoError) {')
w('            appendBubble(ChatBubble::Assistant, QString("\u89e3\u6790\u5931\u8d25\uff1a") + pe.errorString());')
w('            return;')
w('        }')
w('        QJsonObject root = doc.object();')
w('        QString answer;')
w('        QJsonArray choices = root["choices"].toArray();')
w('        if (!choices.isEmpty()) {')
w('            QJsonObject msg = choices[0].toObject()["message"].toObject();')
w('            QJsonValue content = msg["content"];')
w('            if (content.isString()) {')
w('                answer = content.toString();')
w('            } else if (content.isArray()) {')
w('                for (const QJsonValue &v : content.toArray()) {')
w('                    QJsonObject p = v.toObject();')
w('                    if (p["type"].toString() == "text") answer += p["text"].toString();')
w('                }')
w('            }')
w('        }')
w('        if (answer.isEmpty()) {')
w('            if (root.contains("error"))')
w('                answer = QString("\u9519\u8bef\uff1a") + root["error"].toObject()["message"].toString();')
w('            else')
w('                answer = QString("\u672a\u83b7\u53d6\u5230\u56de\u590d");')
w('        }')
w('        appendBubble(ChatBubble::Assistant, answer);')
w('    }')
w('};')
w('')
w('#endif // AICHATWIDGET_H')
out.close()
print('p4 ok')
